import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";
import { useEffect, useState } from "react";
import { useNavigate } from "react-router-dom";
import { ArrowRight, Download, Eye, Search, X } from "lucide-react";
import ClientHubLayout from "../../components/main/ClientHubLayout";
import { getEstimationsByClient } from "../../services/estimationService";

const statusStyles = {
  draft: "bg-gray-100 text-gray-700",
  pending: "bg-yellow-100 text-yellow-700",
  "in-review": "bg-blue-100 text-blue-700",
  approved: "bg-green-100 text-green-700",
  rejected: "bg-red-100 text-red-700",
  completed: "bg-purple-100 text-purple-700",
};

function ClientEstimations() {
  const navigate = useNavigate();
  const [selectedEstimate, setSelectedEstimate] = useState(null);
  const [estimates, setEstimates] = useState([]);
  const [loading, setLoading] = useState(true);
  const [searchTerm, setSearchTerm] = useState("");
  const [statusFilter, setStatusFilter] = useState("all");

  const handleDownload = (estimate) => {
    const doc = new jsPDF();

    // Header
    doc.setFillColor(15, 23, 42);
    doc.rect(0, 0, 210, 30, "F");

    doc.setTextColor(255, 255, 255);
    doc.setFontSize(20);
    doc.text("SMART IT ESTIMATION SYSTEM", 15, 18);

    doc.setTextColor(0, 0, 0);
    doc.setFontSize(16);
    doc.text("Project Estimation Report", 15, 45);

    doc.setFontSize(10);
    doc.text(`Generated: ${new Date().toLocaleDateString()}`, 15, 53);
    doc.text(`Estimate ID: ${estimate._id?.slice(-8).toUpperCase()}`, 150, 53);

    // Client Details Table
    autoTable(doc, {
      startY: 60,
      head: [["Client Information", "Details"]],
      body: [
        ["Client Name", estimate.clientName || "N/A"],
        ["Email", estimate.clientEmail || "N/A"],
        ["Phone", estimate.phone || "N/A"],
        ["Company", estimate.company || "N/A"],
        ["Complexity", estimate.complexity || "N/A"],
      ],
      theme: "striped",
      headStyles: { fillColor: [15, 23, 42], textColor: [255, 255, 255] },
    });

    // Project Details Table
    autoTable(doc, {
      startY: doc.lastAutoTable.finalY + 10,
      head: [["Project Details", "Value"]],
      body: [
        ["Project Type", estimate.projectType?.name || "N/A"],
        ["Timeline", `${estimate.totalDays || 0} Days`],
        ["Total Cost", `₹${estimate.totalCost?.toLocaleString() || 0}`],
        ["Status", estimate.status || "draft"],
      ],
      theme: "striped",
      headStyles: { fillColor: [15, 23, 42], textColor: [255, 255, 255] },
    });

    // Features Table
    if (estimate.features && estimate.features.length > 0) {
      autoTable(doc, {
        startY: doc.lastAutoTable.finalY + 10,
        head: [["Selected Features", "Cost"]],
        body: estimate.features.map(f => [f.name, `₹${(f.cost || 0).toLocaleString()}`]),
        theme: "striped",
        headStyles: { fillColor: [15, 23, 42], textColor: [255, 255, 255] },
      });
    }

    // Footer
    doc.setFontSize(10);
    doc.setTextColor(100, 100, 100);
    doc.text(
      "This is a computer-generated estimate. For any queries, please contact support.",
      15,
      doc.lastAutoTable.finalY + 20
    );
    doc.text(
      "Generated by Smart IT Estimation System",
      15,
      doc.lastAutoTable.finalY + 30
    );

    doc.save(`${estimate.clientName || "client"}_estimate_${estimate._id?.slice(-6)}.pdf`);
  };

  useEffect(() => {
    const fetchData = async () => {
      try {
        const userStr = localStorage.getItem("user");
        let userEmail = null;
        
        if (userStr) {
          try {
            const user = JSON.parse(userStr);
            userEmail = user.email;
          } catch (e) {}
        }
        
        if (!userEmail) {
          userEmail = localStorage.getItem("userEmail") || "shubham@example.com";
        }

        const data = await getEstimationsByClient(userEmail);
        setEstimates(data);
      } catch (error) {
        console.error(error);
      } finally {
        setLoading(false);
      }
    };

    fetchData();
  }, []);

  // Filter estimates based on search and status
  const filteredEstimates = estimates.filter(estimate => {
    // Search filter
    const matchesSearch = 
      estimate.clientName?.toLowerCase().includes(searchTerm.toLowerCase()) ||
      estimate.projectType?.name?.toLowerCase().includes(searchTerm.toLowerCase()) ||
      estimate._id?.slice(-6).toLowerCase().includes(searchTerm.toLowerCase()) ||
      estimate.complexity?.toLowerCase().includes(searchTerm.toLowerCase());
    
    // Status filter
    let matchesStatus = true;
    if (statusFilter === "open") {
      matchesStatus = estimate.status === "draft" || estimate.status === "pending" || estimate.status === "in-review";
    } else if (statusFilter === "closed") {
      matchesStatus = estimate.status === "approved" || estimate.status === "completed" || estimate.status === "rejected";
    } else {
      matchesStatus = statusFilter === "all";
    }
    
    return matchesSearch && matchesStatus;
  });

  // Get status counts
  const getStatusCounts = () => {
    const total = estimates.length;
    const open = estimates.filter(e => e.status === "draft" || e.status === "pending" || e.status === "in-review").length;
    const closed = estimates.filter(e => e.status === "approved" || e.status === "completed" || e.status === "rejected").length;
    return { total, open, closed };
  };

  const counts = getStatusCounts();

  const getStatusBadge = (status) => {
    const statusMap = {
      draft: "Draft",
      pending: "Pending",
      "in-review": "In Review",
      approved: "Approved",
      rejected: "Rejected",
      completed: "Completed"
    };
    return statusMap[status] || status || "Draft";
  };

  const clearSearch = () => {
    setSearchTerm("");
    setStatusFilter("all");
  };

  return (
    <ClientHubLayout activeItem="My Estimates">
      <section className="rounded-[32px] border border-slate-200 bg-white p-6 shadow-sm">
        <div className="flex flex-col gap-4 lg:flex-row lg:items-center lg:justify-between">
          <div>
            <p className="text-sm font-semibold uppercase tracking-[0.24em] text-slate-500">
              Estimate history
            </p>
            <h2 className="mt-2 text-2xl font-black tracking-tight text-slate-950">
              My Estimates
            </h2>
            <p className="mt-2 text-sm text-slate-500">
              Review estimates you created, track status, and continue planning.
            </p>
          </div>

          <button
            onClick={() => navigate("/estimations")}
            className="inline-flex h-11 items-center justify-center gap-2 rounded-xl bg-slate-900 px-5 text-sm font-semibold text-white transition hover:bg-slate-800"
          >
            New Estimate
            <ArrowRight size={16} />
          </button>
        </div>

        <div className="mt-6 flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between">
          {/* Search Bar */}
          <div className="relative flex-1 sm:max-w-sm">
            <Search size={17} className="absolute left-4 top-1/2 -translate-y-1/2 text-slate-400" />
            <input
              type="text"
              value={searchTerm}
              onChange={(e) => setSearchTerm(e.target.value)}
              placeholder="Search by project, client, or estimate ID..."
              className="w-full h-11 rounded-xl border border-slate-200 bg-slate-50 pl-11 pr-10 text-sm font-medium outline-none focus:border-slate-400 focus:ring-2 focus:ring-slate-200"
            />
            {searchTerm && (
              <button
                onClick={() => setSearchTerm("")}
                className="absolute right-3 top-1/2 -translate-y-1/2 text-slate-400 hover:text-slate-600"
              >
                <X size={16} />
              </button>
            )}
          </div>

          {/* Filter Buttons */}
          <div className="flex gap-2">
            <button
              onClick={() => setStatusFilter("all")}
              className={`rounded-xl px-4 py-2.5 text-xs font-semibold transition ${
                statusFilter === "all"
                  ? "bg-slate-900 text-white shadow-md"
                  : "bg-slate-50 text-slate-600 hover:bg-slate-100"
              }`}
            >
              All ({counts.total})
            </button>
            <button
              onClick={() => setStatusFilter("open")}
              className={`rounded-xl px-4 py-2.5 text-xs font-semibold transition ${
                statusFilter === "open"
                  ? "bg-amber-500 text-white shadow-md"
                  : "bg-slate-50 text-slate-600 hover:bg-slate-100"
              }`}
            >
              Open ({counts.open})
            </button>
            <button
              onClick={() => setStatusFilter("closed")}
              className={`rounded-xl px-4 py-2.5 text-xs font-semibold transition ${
                statusFilter === "closed"
                  ? "bg-emerald-500 text-white shadow-md"
                  : "bg-slate-50 text-slate-600 hover:bg-slate-100"
              }`}
            >
              Closed ({counts.closed})
            </button>
          </div>
        </div>

        {/* Results Count */}
        {!loading && (
          <div className="mt-3 text-xs text-slate-500">
            Found {filteredEstimates.length} estimate{filteredEstimates.length !== 1 ? 's' : ''}
            {searchTerm && ` matching "${searchTerm}"`}
            {statusFilter !== "all" && ` with ${statusFilter} status`}
          </div>
        )}

        {/* Table */}
        <div className="mt-4 overflow-hidden rounded-[28px] border border-slate-200">
          {loading ? (
            <div className="p-10 text-center">
              <div className="animate-spin rounded-full h-8 w-8 border-b-2 border-slate-900 mx-auto mb-3"></div>
              <p className="text-slate-500">Loading your estimates...</p>
            </div>
          ) : filteredEstimates.length === 0 ? (
            <div className="p-12 text-center">
              <div className="text-5xl mb-3">📋</div>
              <p className="text-slate-500 font-medium">No estimates found</p>
              <p className="text-sm text-slate-400 mt-1">
                {searchTerm || statusFilter !== "all" 
                  ? "Try adjusting your search or filter criteria"
                  : "Create your first estimate to get started"}
              </p>
              {(searchTerm || statusFilter !== "all") && (
                <button
                  onClick={clearSearch}
                  className="mt-4 text-sm text-slate-600 underline hover:text-slate-900"
                >
                  Clear all filters
                </button>
              )}
              {!searchTerm && statusFilter === "all" && estimates.length === 0 && (
                <button
                  onClick={() => navigate("/estimations")}
                  className="mt-4 inline-flex items-center gap-2 rounded-xl bg-slate-900 px-4 py-2 text-sm font-semibold text-white"
                >
                  Create New Estimate
                  <ArrowRight size={14} />
                </button>
              )}
            </div>
          ) : (
            <div className="overflow-x-auto">
              <table className="min-w-full text-left text-sm">
                <thead className="bg-slate-50 text-slate-500">
                  <tr>
                    <th className="px-4 py-4 font-semibold">Estimate</th>
                    <th className="px-4 py-4 font-semibold">Project / Client</th>
                    <th className="px-4 py-4 font-semibold">Type</th>
                    <th className="px-4 py-4 font-semibold">Amount</th>
                    <th className="px-4 py-4 font-semibold">Timeline</th>
                    <th className="px-4 py-4 font-semibold">Complexity</th>
                    <th className="px-4 py-4 font-semibold">Status</th>
                    <th className="px-4 py-4 font-semibold">Created</th>
                    <th className="px-4 py-4 font-semibold text-center">Actions</th>
                  </tr>
                </thead>
                <tbody className="bg-white">
                  {filteredEstimates.map((estimate) => (
                    <tr key={estimate._id} className="border-t border-slate-200 hover:bg-slate-50 transition">
                      <td className="px-4 py-4 font-mono font-bold text-slate-950">
                        {estimate._id.slice(-6).toUpperCase()}
                      </td>
                      <td className="px-4 py-4">
                        <div className="font-semibold text-slate-900">{estimate.clientName || "N/A"}</div>
                        <div className="text-xs text-slate-400">{estimate.projectType?.name || "N/A"}</div>
                      </td>
                      <td className="px-4 py-4 text-slate-600">
                        <span className="inline-flex px-2 py-1 rounded-full text-xs bg-gray-100">
                          {estimate.projectType?.name?.slice(0, 15) || "N/A"}
                        </span>
                      </td>
                      <td className="px-4 py-4 font-semibold text-slate-900">
                        ₹{estimate.totalCost?.toLocaleString() || 0}
                      </td>
                      <td className="px-4 py-4 text-slate-600">{estimate.totalDays || 0} Days</td>
                      <td className="px-4 py-4">
                        <span className={`inline-flex px-2 py-1 rounded-full text-xs font-medium ${
                          estimate.complexity === "High" ? "bg-red-100 text-red-700" :
                          estimate.complexity === "Medium" ? "bg-yellow-100 text-yellow-700" :
                          "bg-green-100 text-green-700"
                        }`}>
                          {estimate.complexity || "Medium"}
                        </span>
                      </td>
                      <td className="px-4 py-4">
                        <span className={`inline-flex px-2 py-1 rounded-full text-xs font-medium ${statusStyles[estimate.status] || statusStyles.draft}`}>
                          {getStatusBadge(estimate.status)}
                        </span>
                      </td>
                      <td className="px-4 py-4 text-slate-600">
                        {new Date(estimate.createdAt).toLocaleDateString('en-US', { 
                          year: 'numeric', 
                          month: 'short', 
                          day: 'numeric' 
                        })}
                      </td>
                      <td className="px-4 py-4">
                        <div className="flex items-center justify-end gap-2">
                          <button
                            onClick={() => setSelectedEstimate(estimate)}
                            className="grid h-8 w-8 place-items-center rounded-xl border border-slate-200 bg-white text-slate-700 transition hover:bg-slate-100 hover:border-slate-300"
                            title="View Details"
                          >
                            <Eye size={15} />
                          </button>
                          <button
                            onClick={() => handleDownload(estimate)}
                            className="grid h-8 w-8 place-items-center rounded-xl bg-slate-900 text-white transition hover:bg-slate-800"
                            title="Download PDF"
                          >
                            <Download size={15} />
                          </button>
                        </div>
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          )}
        </div>
      </section>

      {/* View Estimate Modal */}
      {selectedEstimate && (
        <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/50" onClick={() => setSelectedEstimate(null)}>
          <div className="w-full max-w-lg rounded-3xl bg-white p-6 shadow-xl" onClick={(e) => e.stopPropagation()}>
            <div className="flex items-center justify-between">
              <h2 className="text-2xl font-bold">Estimate Details</h2>
              <button
                onClick={() => setSelectedEstimate(null)}
                className="w-8 h-8 rounded-full bg-gray-100 flex items-center justify-center hover:bg-gray-200 transition"
              >
                <X size={18} />
              </button>
            </div>

            <div className="mt-6 space-y-4">
              <div className="grid grid-cols-2 gap-4">
                <div>
                  <p className="text-sm text-slate-500">Estimate ID</p>
                  <p className="font-mono font-semibold">{selectedEstimate._id.slice(-8).toUpperCase()}</p>
                </div>
                <div>
                  <p className="text-sm text-slate-500">Created</p>
                  <p className="font-semibold">{new Date(selectedEstimate.createdAt).toLocaleDateString()}</p>
                </div>
              </div>

              <div>
                <p className="text-sm text-slate-500">Client Name</p>
                <p className="font-semibold">{selectedEstimate.clientName || "N/A"}</p>
              </div>

              <div>
                <p className="text-sm text-slate-500">Email</p>
                <p className="font-semibold">{selectedEstimate.clientEmail || "N/A"}</p>
              </div>

              <div>
                <p className="text-sm text-slate-500">Project Type</p>
                <p className="font-semibold">{selectedEstimate.projectType?.name || "N/A"}</p>
              </div>

              <div className="grid grid-cols-2 gap-4">
                <div>
                  <p className="text-sm text-slate-500">Total Cost</p>
                  <p className="text-xl font-black text-slate-900">₹{selectedEstimate.totalCost?.toLocaleString() || 0}</p>
                </div>
                <div>
                  <p className="text-sm text-slate-500">Timeline</p>
                  <p className="text-xl font-black text-slate-900">{selectedEstimate.totalDays || 0} Days</p>
                </div>
              </div>

              <div className="grid grid-cols-2 gap-4">
                <div>
                  <p className="text-sm text-slate-500">Complexity</p>
                  <p className={`inline-flex px-3 py-1 rounded-full text-sm font-medium ${
                    selectedEstimate.complexity === "High" ? "bg-red-100 text-red-700" :
                    selectedEstimate.complexity === "Medium" ? "bg-yellow-100 text-yellow-700" :
                    "bg-green-100 text-green-700"
                  }`}>
                    {selectedEstimate.complexity || "Medium"}
                  </p>
                </div>
                <div>
                  <p className="text-sm text-slate-500">Status</p>
                  <p className={`inline-flex px-3 py-1 rounded-full text-sm font-medium ${statusStyles[selectedEstimate.status] || statusStyles.draft}`}>
                    {getStatusBadge(selectedEstimate.status)}
                  </p>
                </div>
              </div>

              {selectedEstimate.features && selectedEstimate.features.length > 0 && (
                <div>
                  <p className="text-sm text-slate-500 mb-2">Selected Features</p>
                  <div className="space-y-1 max-h-32 overflow-y-auto">
                    {selectedEstimate.features.map((f, idx) => (
                      <div key={idx} className="text-sm flex justify-between">
                        <span>{f.name}</span>
                        <span className="font-medium">₹{(f.cost || 0).toLocaleString()}</span>
                      </div>
                    ))}
                  </div>
                </div>
              )}
            </div>

            <div className="mt-6 flex gap-3">
              <button
                onClick={() => handleDownload(selectedEstimate)}
                className="flex-1 h-10 rounded-xl bg-slate-900 text-white font-semibold flex items-center justify-center gap-2 hover:bg-slate-800"
              >
                <Download size={16} />
                Download PDF
              </button>
              <button
                onClick={() => setSelectedEstimate(null)}
                className="flex-1 h-10 rounded-xl border border-slate-200 font-semibold hover:bg-slate-50"
              >
                Close
              </button>
            </div>
          </div>
        </div>
      )}
    </ClientHubLayout>
  );
}

export default ClientEstimations;