import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";
import { useEffect, useState } from "react";
import { useNavigate } from "react-router-dom";
import { ArrowRight, Download, Eye, Search } from "lucide-react";
import ClientHubLayout from "../../components/main/ClientHubLayout";
import { getEstimationsByClient } from "../../services/estimationService";




function ClientEstimations() {
  const navigate = useNavigate();
  const [selectedEstimate, setSelectedEstimate] = useState(null);
  const [estimates, setEstimates] = useState([]);
const [loading, setLoading] = useState(true);
const handleDownload = (estimate) => {
  const doc = new jsPDF();

  // Header
  doc.setFillColor(15, 23, 42);
  doc.rect(0, 0, 210, 30, "F");

  doc.setTextColor(255, 255, 255);
  doc.setFontSize(20);
  doc.text("SMART IT ESTIMATION SYSTEM", 15, 18);

  // Reset color
  doc.setTextColor(0, 0, 0);

  doc.setFontSize(16);
  doc.text("Project Estimation Report", 15, 45);

  doc.setFontSize(10);
  doc.text(
    `Generated: ${new Date().toLocaleDateString()}`,
    15,
    53
  );

  // Client Details Table
  autoTable(doc, {
    startY: 60,
    head: [["Client Information", "Details"]],
    body: [
      ["Client Name", estimate.clientName || "N/A"],
      ["Email", estimate.clientEmail || "N/A"],
      ["Complexity", estimate.complexity || "N/A"],
    ],
  });

  // Project Details Table
  autoTable(doc, {
    startY: doc.lastAutoTable.finalY + 10,
    head: [["Project Details", "Value"]],
    body: [
      [
        "Project Type",
        estimate.projectType?.name || "N/A",
      ],
      [
        "Timeline",
        `${estimate.totalDays || 0} Days`,
      ],
      [
        "Total Cost",
        `₹${estimate.totalCost?.toLocaleString() || 0}`,
      ],
    ],
  });

  // Footer
  doc.setFontSize(10);
  doc.text(
    "Generated by Smart IT Estimation System",
    15,
    doc.lastAutoTable.finalY + 25
  );

  doc.save(
    `${estimate.clientName || "client"}-estimate.pdf`
  );
};

useEffect(() => {
  const fetchData = async () => {
    try {
      const user = JSON.parse(localStorage.getItem("user"));

      if (!user?.email) {
        setLoading(false);
        return;
      }

      const data = await getEstimationsByClient(user.email);

      setEstimates(data);
    } catch (error) {
      console.error(error);
    } finally {
      setLoading(false);
    }
  };

  fetchData();
}, []);
  return (
    <ClientHubLayout activeItem="My Estimates">
      <section className="rounded-[32px] border border-slate-200 bg-white p-6 shadow-sm">
        <div className="flex flex-col gap-4 lg:flex-row lg:items-center lg:justify-between">
          <div>
            <p className="text-sm font-semibold uppercase tracking-[0.24em] text-slate-500">
              Estimate history
            </p>
            <h2 className="mt-2 text-2xl font-black tracking-tight text-slate-950">
              My Estimates
            </h2>
            <p className="mt-2 text-sm text-slate-500">
              Review estimates you created, track status, and continue planning.
            </p>
          </div>

          <button
            onClick={() => navigate("/estimations")}
            className="inline-flex h-11 items-center justify-center gap-2 rounded-xl bg-slate-900 px-5 text-sm font-semibold text-white transition hover:bg-slate-800"
          >
            New Estimate
            <ArrowRight size={16} />
          </button>
        </div>

        <div className="mt-6 flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between">
          <label className="flex h-11 w-full items-center gap-3 rounded-xl border border-slate-200 bg-slate-50 px-4 sm:max-w-sm">
            <Search size={17} className="text-slate-500" />
            <input
              className="w-full bg-transparent text-sm font-medium outline-none placeholder:text-slate-400"
              placeholder="Search estimates"
              type="search"
            />
          </label>

          <div className="grid grid-cols-3 gap-2 text-center text-xs font-semibold text-slate-600 sm:w-auto">
            <span className="rounded-xl bg-slate-50 px-4 py-3">All 4</span>
            <span className="rounded-xl bg-slate-50 px-4 py-3">Open 2</span>
            <span className="rounded-xl bg-slate-50 px-4 py-3">Closed 1</span>
          </div>
        </div>

        <div className="mt-6 overflow-hidden rounded-[28px] border border-slate-200">
          {loading ? (
  <div className="p-10 text-center">
    Loading...
  </div>
) : estimates.length === 0 ? (
  <div className="p-10 text-center text-slate-500">
    No estimations found.
  </div>
) : (
          <table className="min-w-full text-left text-sm">
            <thead className="bg-slate-50 text-slate-500">
              <tr>
                {[
                  "Estimate",
                  "Project",
                  "Type",
                  "Amount",
                  "Timeline",
                  "Complexity",
                  "Status",
                  "Created",
                  "",
                ].map((label) => (
                  <th key={label} className="px-4 py-4 font-semibold">
                    {label}
                  </th>
                ))}
              </tr>
            </thead>
            <tbody className="bg-white">
              {estimates.map((estimate) => (
                <tr key={estimate._id.slice(-6)} className="border-t border-slate-200 hover:bg-slate-50">
                  <td className="px-4 py-4 font-black text-slate-950">{estimate._id.slice(-6)}</td>
                  <td className="px-4 py-4 font-semibold text-slate-900">{estimate.projectType?.name}</td>
                  <td className="px-4 py-4 text-slate-600">{estimate.projectType?.name}</td>
                  <td className="px-4 py-4 font-semibold text-slate-900">₹{estimate.totalCost?.toLocaleString()}</td>
                  <td className="px-4 py-4 text-slate-600">{estimate.totalDays} Days</td>
                  <td className="px-4 py-4 text-slate-600">{estimate.complexity}</td>
                  <td className="px-4 py-4">
                    
                  </td>
                  <td className="px-4 py-4 text-slate-600">{new Date(estimate.createdAt).toLocaleDateString()}</td>
                  <td className="px-4 py-4">
                    <div className="flex items-center justify-end gap-2">
                      <button
  onClick={() => setSelectedEstimate(estimate)}
  className="grid h-9 w-9 place-items-center rounded-xl border border-slate-200 bg-white text-slate-700 transition hover:bg-slate-100"
>
  <Eye size={16} />
</button>
                      <button
  onClick={() => handleDownload(estimate)}
  className="grid h-9 w-9 place-items-center rounded-xl bg-slate-900 text-white transition hover:bg-slate-800"
>
  <Download size={16} />
</button>
                    </div>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
          )}
        </div>
      </section>
      {selectedEstimate && (
  <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/50">
    <div className="w-full max-w-lg rounded-3xl bg-white p-6 shadow-xl">
      <div className="flex items-center justify-between">
        <h2 className="text-2xl font-bold">
          Estimate Details
        </h2>

        <button
          onClick={() => setSelectedEstimate(null)}
          className="text-xl font-bold"
        >
          ✕
        </button>
      </div>

      <div className="mt-6 space-y-4">

        <div>
          <p className="text-sm text-slate-500">
            Project
          </p>

          <p className="font-semibold">
            {selectedEstimate.projectType?.name}
          </p>
        </div>

        <div>
          <p className="text-sm text-slate-500">
            Cost
          </p>

          <p className="font-semibold">
            ₹{selectedEstimate.totalCost?.toLocaleString()}
          </p>
        </div>

        <div>
          <p className="text-sm text-slate-500">
            Timeline
          </p>

          <p className="font-semibold">
            {selectedEstimate.totalDays} Days
          </p>
        </div>

        <div>
          <p className="text-sm text-slate-500">
            Complexity
          </p>

          <p className="font-semibold">
            {selectedEstimate.complexity}
          </p>
        </div>

      </div>
    </div>
  </div>
)}
    </ClientHubLayout>
  );
}

export default ClientEstimations;